Change default for `check_mac_release(dep_pkgs =)`
At the very least, the default of `"."` causes a failed attempt to delete the built package twice. It also seems like it could cause redundant building or uploading (?).

Error: [ENOENT] Failed to remove '/tmp/Rtmpfwijli/usethis_2.1.3.9000.tar.gz': no such file or directory