Fix error message in release()
It was missing a newline

```
Error: Can't find cran-comments.md in withr.
This file gives CRAN volunteers comments about the submission,
and it must exist.  Please create it using this guide:
http://r-pkgs.had.co.nz/release.html#release-checkThen run use_build_ignore('cran-comments.md')
```